"""Static data tables: social/react action catalogs, 8-ball pools, RPS, and the
derived nekos.best endpoint list."""

from utils import helpers as h

from .constants import _PINK

_SOCIAL_ACTIONS: dict[str, dict] = {
    "bite": {
        "endpoint": "bite",
        "label": "bite",
        "bot_msg": "Hope you like the taste of silicon. \U0001f9db",
        "self_msg": "Biting yourself? Ouch! \U0001f9db",
        "action_msg": "{author} bites {target}! \U0001f9db",
        "color": h.RED,
        "desc": "Bite someone!",
        "short": "Bite someone",
    },
    "blowkiss": {
        "endpoint": "blowkiss",
        "label": "blow kiss",
        "bot_msg": "A blown kiss for a bot? Caught it! \U0001f618",
        "self_msg": "Blowing yourself a kiss? Self-love! \U0001f618",
        "action_msg": "{author} blows a kiss at {target}! \U0001f618",
        "color": _PINK,
        "desc": "Blow someone a kiss!",
        "short": "Blow someone a kiss",
    },
    "bonk": {
        "endpoint": "bonk",
        "label": "bonk",
        "bot_msg": "You can't bonk the bot! \U0001f916",
        "self_msg": "Bonking yourself? Straight to horny jail. \U0001f528",
        "action_msg": "{author} bonks {target}! \U0001f528",
        "color": h.YELLOW,
        "desc": "Bonk someone!",
        "short": "Bonk someone",
    },
    "boop": {
        "endpoint": "pat",
        "label": "boop",
        "bot_msg": "Boop accepted. Boop logged. \U0001f916",
        "self_msg": "Booping your own snoot? Certified legend. \U0001f446",
        "action_msg": "{author} boops {target}'s snoot! \U0001f446",
        "color": 0xFFC0CB,
        "desc": "Boop someone's snoot!",
        "short": "Boop the snoot",
    },
    "cheekskiss": {
        "endpoint": "kiss",
        "label": "cheek kiss",
        "bot_msg": "A cheek kiss for a bot? How adorable! \U0001f60a",
        "self_msg": "Mwah! Loving yourself is important. \U0001f618",
        "action_msg": "{author} gives {target} a little cheek kiss! \U0001f618",
        "color": _PINK,
        "desc": "Give someone a sweet cheek kiss!",
        "short": "Give a cheek kiss",
    },
    "cuddle": {
        "endpoint": "cuddle",
        "label": "cuddle",
        "bot_msg": "Cuddling a bot? I'm flattered. \U0001f97a",
        "self_msg": "Self-cuddle activated. \U0001f97a",
        "action_msg": "{author} cuddles {target}! \U0001f97a",
        "color": _PINK,
        "desc": "Cuddle someone!",
        "short": "Cuddle someone",
    },
    "feed": {
        "endpoint": "feed",
        "label": "feed",
        "bot_msg": "I run on electricity, but thanks! \u26a1",
        "self_msg": "Feeding yourself? Self-care. \U0001f35c",
        "action_msg": "{author} feeds {target}! \U0001f35c",
        "color": _PINK,
        "desc": "Feed someone!",
        "short": "Feed someone",
    },
    "handhold": {
        "endpoint": "handhold",
        "label": "hand hold",
        "bot_msg": "H-holding hands?! How lewd! \U0001f633",
        "self_msg": "That's called clasping. \U0001f91d",
        "action_msg": "{author} holds {target}'s hand! \U0001f91d",
        "color": _PINK,
        "desc": "Hold someone's hand!",
        "short": "Hold someone's hand",
    },
    "handshake": {
        "endpoint": "handshake",
        "label": "handshake",
        "bot_msg": "*firm handshake* Pleasure doing business. \U0001f916",
        "self_msg": "Deal with yourself sealed. \U0001f91d",
        "action_msg": "{author} shakes {target}'s hand! \U0001f91d",
        "color": h.BLUE,
        "desc": "Shake someone's hand!",
        "short": "Shake someone's hand",
    },
    "highfive": {
        "endpoint": "highfive",
        "label": "high five",
        "bot_msg": "\u270b *high fives back*",
        "self_msg": "A self-high-five? Respect. \U0001f64c",
        "action_msg": "{author} high fives {target}! \U0001f64c",
        "color": h.GREEN,
        "desc": "High five someone!",
        "short": "High five someone",
    },
    "hug": {
        "endpoint": "hug",
        "label": "hug",
        "bot_msg": "I'm just a bot, but I'd never turn down a hug! \U0001f917",
        "self_msg": "Awh, no one to hug? Don't worry, I've got you. \U0001f917",
        "action_msg": "{author} hugs {target}! \U0001f917",
        "color": _PINK,
        "desc": "Give someone a warm hug.",
        "short": "Give someone a hug",
    },
    "kick": {
        "endpoint": "kick",
        "label": "kick",
        "bot_msg": "You can't kick me! I live in the cloud! \u2601\ufe0f",
        "self_msg": "Kicking yourself? Bold. \U0001f9b5",
        "action_msg": "{author} kicks {target}! \U0001f9b5",
        "color": h.YELLOW,
        "desc": "Kick someone (for fun)!",
        "short": "Fun-kick someone",
    },
    "kiss": {
        "endpoint": "kiss",
        "label": "kiss",
        "bot_msg": "I appreciate the affection, but I'm made of code! \U0001f4be\U0001f48b",
        "self_msg": "Kissing yourself? Absolute power move. \U0001f48b",
        "action_msg": "{author} kisses {target}! \U0001f48b",
        "color": _PINK,
        "desc": "Kiss someone!",
        "short": "Kiss someone",
    },
    "lappillow": {
        "endpoint": "lappillow",
        "label": "lap pillow",
        "bot_msg": "A bot lap pillow? I'll allow it. \U0001f60c",
        "self_msg": "Lap pillow for one? Cozy. \U0001f60c",
        "action_msg": "{author} offers {target} a lap pillow! \U0001f60c",
        "color": _PINK,
        "desc": "Offer someone a lap pillow!",
        "short": "Offer a lap pillow",
    },
    "nom": {
        "endpoint": "nom",
        "label": "nom",
        "bot_msg": "I taste like 1s and 0s. \U0001f916",
        "self_msg": "Snack attack! \U0001f60b",
        "action_msg": "{author} noms on {target}! \U0001f60b",
        "color": _PINK,
        "desc": "Nom on someone!",
        "short": "Nom on someone",
    },
    "pat": {
        "endpoint": "pat",
        "label": "pat",
        "bot_msg": "*enjoys the headpats* \u2728 Thank you!",
        "self_msg": "Pat yourself on the back -- you deserve it! \U0001f972",
        "action_msg": "{author} gives {target} a comforting pat! \U0001f970",
        "color": 0xFFC0CB,
        "desc": "Give someone a comforting head pat.",
        "short": "Head pat someone",
    },
    "peck": {
        "endpoint": "peck",
        "label": "peck",
        "bot_msg": "A peck for a bot? Sweet! \U0001f60a",
        "self_msg": "Pecking yourself? Cute. \U0001f617",
        "action_msg": "{author} gives {target} a quick peck! \U0001f617",
        "color": _PINK,
        "desc": "Give someone a quick peck!",
        "short": "Give a quick peck",
    },
    "poke": {
        "endpoint": "poke",
        "label": "poke",
        "bot_msg": "Hey! No poking the bot! \U0001f916\U0001f448",
        "self_msg": "...why are you poking yourself? \U0001f448",
        "action_msg": "{author} pokes {target}! \U0001f449",
        "color": h.YELLOW,
        "desc": "Poke someone!",
        "short": "Poke someone",
    },
    "punch": {
        "endpoint": "punch",
        "label": "punch",
        "bot_msg": "*dodges* Try harder! \U0001f916",
        "self_msg": "Punching yourself? Respect. \U0001f91c",
        "action_msg": "{author} punches {target}! \U0001f91c",
        "color": h.RED,
        "desc": "Punch someone!",
        "short": "Punch someone",
    },
    "shake": {
        "endpoint": "shake",
        "label": "shake",
        "bot_msg": "Stop shaking me! My circuits are rattling! \U0001fae8",
        "self_msg": "Shaking yourself? Everything okay? \U0001fae8",
        "action_msg": "{author} shakes {target}! \U0001fae8",
        "color": h.YELLOW,
        "desc": "Shake someone!",
        "short": "Shake someone",
    },
    "shoot": {
        "endpoint": "shoot",
        "label": "shoot",
        "bot_msg": "*deflects* No u. \U0001f916",
        "self_msg": "Pew pew at yourself! \U0001f449",
        "action_msg": "{author} shoots {target}! Pew pew! \U0001f449",
        "color": h.RED,
        "desc": "Finger guns!",
        "short": "Finger-gun someone",
    },
    "slap": {
        "endpoint": "slap",
        "label": "slap",
        "bot_msg": "You can't slap me, I'm intangible! \U0001f916",
        "self_msg": "Slapping yourself? That's rough. \U0001f612",
        "action_msg": "{author} slaps {target}! \U0001f44f",
        "color": h.RED,
        "desc": "Slap someone!",
        "short": "Slap someone",
    },
    "stare": {
        "endpoint": "stare",
        "label": "stare",
        "bot_msg": "*stares back in binary* \U0001f440",
        "self_msg": "Introspection is healthy. \U0001f440",
        "action_msg": "{author} stares at {target}! \U0001f440",
        "color": h.BLUE,
        "desc": "Stare at someone!",
        "short": "Stare at someone",
    },
    "tickle": {
        "endpoint": "tickle",
        "label": "tickle",
        "bot_msg": "I'm not ticklish! ...or am I? \U0001f914",
        "self_msg": "Tickling yourself doesn't work. \U0001f923",
        "action_msg": "{author} tickles {target}! \U0001f923",
        "color": h.YELLOW,
        "desc": "Tickle someone!",
        "short": "Tickle someone",
    },
    "wave": {
        "endpoint": "wave",
        "label": "wave",
        "bot_msg": "\U0001f44b Hello there!",
        "self_msg": "Waving at yourself? I wave back! \U0001f44b",
        "action_msg": "{author} waves at {target}! \U0001f44b",
        "color": h.BLUE,
        "desc": "Wave at someone!",
        "short": "Wave at someone",
    },
    "yeet": {
        "endpoint": "yeet",
        "label": "yeet",
        "bot_msg": "You can't yeet the un-yeetable! \U0001f916",
        "self_msg": "Yeeting yourself? Godspeed. \U0001f680",
        "action_msg": "{author} yeets {target} into orbit! \U0001f680",
        "color": h.YELLOW,
        "desc": "Yeet someone into orbit!",
        "short": "Yeet someone",
    },
}

# -- Solo reactions: express yourself -----------------------------------------
_REACT_ACTIONS: dict[str, dict] = {
    "angry": {
        "endpoint": "angry",
        "label": "angry",
        "msg": "{author} is angry! \U0001f620",
        "color": h.RED,
        "desc": "Be angry!",
        "short": "Be angry",
    },
    "baka": {
        "endpoint": "baka",
        "label": "baka",
        "msg": "{author} yells BAKA! \U0001f621",
        "color": h.RED,
        "desc": "Yell BAKA!",
        "short": "Baka!",
    },
    "bleh": {
        "endpoint": "bleh",
        "label": "bleh",
        "msg": "{author} sticks their tongue out! \U0001f61d",
        "color": h.YELLOW,
        "desc": "Stick your tongue out!",
        "short": "Stick your tongue out",
    },
    "blush": {
        "endpoint": "blush",
        "label": "blush",
        "msg": "{author} is blushing! \U0001f633",
        "color": _PINK,
        "desc": "Blush!",
        "short": "Blush",
    },
    "bored": {
        "endpoint": "bored",
        "label": "bored",
        "msg": "{author} is bored... \U0001f971",
        "color": _PINK,
        "desc": "Be bored.",
        "short": "Be bored",
    },
    "clap": {
        "endpoint": "clap",
        "label": "clap",
        "msg": "{author} is clapping! \U0001f44f",
        "color": h.GREEN,
        "desc": "Clap!",
        "short": "Clap",
    },
    "confused": {
        "endpoint": "confused",
        "label": "confused",
        "msg": "{author} is confused... \U0001f615",
        "color": h.YELLOW,
        "desc": "Be confused.",
        "short": "Be confused",
    },
    "cry": {
        "endpoint": "cry",
        "label": "cry",
        "msg": "{author} is crying... \U0001f622",
        "color": _PINK,
        "desc": "Express your sadness.",
        "short": "Cry",
    },
    "dance": {
        "endpoint": "dance",
        "label": "dance",
        "msg": "{author} is dancing! \U0001f57a",
        "color": h.GREEN,
        "desc": "Show off your moves!",
        "short": "Dance",
    },
    "facepalm": {
        "endpoint": "facepalm",
        "label": "facepalm",
        "msg": "{author} facepalms. \U0001f926",
        "color": h.YELLOW,
        "desc": "Facepalm.",
        "short": "Facepalm",
    },
    "happy": {
        "endpoint": "happy",
        "label": "happy",
        "msg": "{author} is happy! \U0001f60a",
        "color": h.GREEN,
        "desc": "Be happy!",
        "short": "Be happy",
    },
    "laugh": {
        "endpoint": "laugh",
        "label": "laugh",
        "msg": "{author} is laughing! \U0001f602",
        "color": h.YELLOW,
        "desc": "Laugh out loud!",
        "short": "Laugh",
    },
    "lurk": {
        "endpoint": "lurk",
        "label": "lurk",
        "msg": "{author} is lurking... \U0001f440",
        "color": h.BLUE,
        "desc": "Lurk in the shadows.",
        "short": "Lurk",
    },
    "nod": {
        "endpoint": "nod",
        "label": "nod",
        "msg": "{author} nods. \U0001f642",
        "color": _PINK,
        "desc": "Nod.",
        "short": "Nod",
    },
    "nope": {
        "endpoint": "nope",
        "label": "nope",
        "msg": "{author} says NOPE. \U0001f645",
        "color": h.RED,
        "desc": "Nope!",
        "short": "Nope",
    },
    "nya": {
        "endpoint": "nya",
        "label": "nya",
        "msg": "{author} goes nya~! \U0001f431",
        "color": _PINK,
        "desc": "Go nya~!",
        "short": "Nya~!",
    },
    "pout": {
        "endpoint": "pout",
        "label": "pout",
        "msg": "{author} is pouting! \U0001f61e",
        "color": _PINK,
        "desc": "Pout!",
        "short": "Pout",
    },
    "run": {
        "endpoint": "run",
        "label": "run",
        "msg": "{author} is running away! \U0001f3c3",
        "color": h.YELLOW,
        "desc": "Run away!",
        "short": "Run away",
    },
    "salute": {
        "endpoint": "salute",
        "label": "salute",
        "msg": "{author} salutes! \U0001fae1",
        "color": h.BLUE,
        "desc": "Salute!",
        "short": "Salute",
    },
    "shocked": {
        "endpoint": "shocked",
        "label": "shocked",
        "msg": "{author} is shocked! \U0001f631",
        "color": h.YELLOW,
        "desc": "Be shocked!",
        "short": "Be shocked",
    },
    "shrug": {
        "endpoint": "shrug",
        "label": "shrug",
        "msg": "{author} shrugs. \U0001f937",
        "color": _PINK,
        "desc": "Shrug it off.",
        "short": "Shrug",
    },
    "sip": {
        "endpoint": "sip",
        "label": "sip",
        "msg": "{author} takes a sip... \u2615",
        "color": h.BLUE,
        "desc": "Take a sip.",
        "short": "Take a sip",
    },
    "sleep": {
        "endpoint": "sleep",
        "label": "sleep",
        "msg": "{author} is sleeping... zzZ \U0001f634",
        "color": h.BLUE,
        "desc": "Sleepy time.",
        "short": "Sleep",
    },
    "smile": {
        "endpoint": "smile",
        "label": "smile",
        "msg": "{author} smiles! \U0001f60a",
        "color": h.GREEN,
        "desc": "Smile!",
        "short": "Smile",
    },
    "smug": {
        "endpoint": "smug",
        "label": "smug",
        "msg": "{author} looks smug. \U0001f60f",
        "color": _PINK,
        "desc": "Look smug.",
        "short": "Look smug",
    },
    "spin": {
        "endpoint": "spin",
        "label": "spin",
        "msg": "{author} is spinning! \U0001f300",
        "color": h.GREEN,
        "desc": "Spin!",
        "short": "Spin",
    },
    "tableflip": {
        "endpoint": "tableflip",
        "label": "table flip",
        "msg": "{author} flips the table! (\u256f\u00b0\u25a1\u00b0)\u256f\ufe35 \u253b\u2501\u253b",
        "color": h.RED,
        "desc": "Flip the table!",
        "short": "Flip the table",
    },
    "teehee": {
        "endpoint": "teehee",
        "label": "teehee",
        "msg": "{author} giggles... teehee! \U0001f92d",
        "color": _PINK,
        "desc": "Giggle!",
        "short": "Teehee!",
    },
    "think": {
        "endpoint": "think",
        "label": "think",
        "msg": "{author} is thinking... \U0001f914",
        "color": h.BLUE,
        "desc": "Think hard.",
        "short": "Think",
    },
    "thumbsup": {
        "endpoint": "thumbsup",
        "label": "thumbs up",
        "msg": "{author} gives a thumbs up! \U0001f44d",
        "color": h.GREEN,
        "desc": "Give a thumbs up!",
        "short": "Thumbs up",
    },
    "wag": {
        "endpoint": "wag",
        "label": "wag",
        "msg": "{author} wags their tail! \U0001f415",
        "color": h.GREEN,
        "desc": "Wag your tail!",
        "short": "Wag your tail",
    },
    "wink": {
        "endpoint": "wink",
        "label": "wink",
        "msg": "{author} winks! \U0001f609",
        "color": _PINK,
        "desc": "Wink!",
        "short": "Wink",
    },
    "yawn": {
        "endpoint": "yawn",
        "label": "yawn",
        "msg": "{author} yawns... \U0001f971",
        "color": _PINK,
        "desc": "Yawn.",
        "short": "Yawn",
    },
}


# ── 8-ball pools ──────────────────────────────────────────────────────────────
_8BALL_POSITIVE = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
]
_8BALL_NEUTRAL = [
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
]
_8BALL_NEGATIVE = [
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful.",
]

# ── Rock Paper Scissors ──────────────────────────────────────────────────────
_RPS_CHOICES = {"rock": "\u270a", "paper": "\u270b", "scissors": "\u2702\ufe0f"}
_RPS_WINS = {"rock": "scissors", "scissors": "paper", "paper": "rock"}
_RPS_COLOR = 0x5865F2


# Images cog endpoints (static images, not GIFs -- scraped the same way)
_IMAGE_ENDPOINTS = ("husbando", "kitsune", "neko", "waifu")

# All unique nekos.best endpoints across social + react + images
_ALL_NEKOS_ENDPOINTS: tuple[str, ...] = tuple(
    sorted(
        {d["endpoint"] for d in _SOCIAL_ACTIONS.values()}
        | {d["endpoint"] for d in _REACT_ACTIONS.values()}
        | set(_IMAGE_ENDPOINTS)
    )
)
